### ISSUE TITLE
Social tiles have started saying "Page not found"

### ISSUE THREAD

**Issue by krook** [cncf/cncf.io#834] opened 2024-02-06 14:20 UTC
Seems like there's been a rather recent change to the social tiles on LinkedIn, at least. The shared URL is correct, but the metadata returns "Page not found" as its title.

<img width="525" alt="linkedin-metadata" src="https://github.com/cncf/cncf.io/assets/1499840/d92d8e25-a009-412a-9cb1-88c4eabeb656">

**Comment by thetwopct** [comment] 2024-02-06 15:53
## To fix the image preview 

To fix the preview, I think the post could be edited on Linkedin. To trigger Linkedin to check for a new image, the URL in the post just needs to be updated/changed slightly. So if the URL is removed and then the same URL with a query parameter is added it should force update the picture. 

Existing URL:

`https://www.cncf.io/blog/2024/02/02/oracle-oci-credits-are-now-available-to-cncf-projects-here-is-what-you-need-to-know/`

Suggested new URL:

`https://www.cncf.io/blog/2024/02/02/oracle-oci-credits-are-now-available-to-cncf-projects-here-is-what-you-need-to-know/?latest`

(note the addition of `?latest` at the end of the URL)

If that doesn't work, the social share image for the post could be added directly to the post and this would replace the link preview. The image can be [downloaded here](https://www.cncf.io/wp-content/uploads/2024/02/Single-Card-28.png). 

## Root cause of the issue

To fix the root of the issue, we should look at the post that was [created on LinkedIn](https://www.linkedin.com/posts/cloud-native-computing-foundation_page-not-found-cncf-activity-7159214389189910528-NXhN):

`https://www.linkedin.com/posts/cloud-native-computing-foundation_page-not-found-cncf-activity-7159214389189910528-NXhN`

From the URL for the post on Linkedin, it wasn't just the image that was not found or not being seen, it was also the blog post itself was registered as "_Page not found_" (`page-not-found-cncf-activity` in the direct post URL)

Looking at WordPress, the blog post was published Febraury 2, 2024 at 08:00 and looking at the logs this seems to be true. 

All CNCF social media posts are scheduled and published via HubSpot. The LinkedIn post was scheduled and published via HubSpot and was scheduled for Febraury 2, 2024 at 08:02. But we don't have any logs or exact time it was published.

But, HubSpot has a feature called "Publish like a human" which makes the posts publish at random times within 10 minutes of the scheduled time.

![Screenshot-2024-02-06 --22 45 19](https://github.com/cncf/cncf.io/assets/10615884/1f08d826-9797-4160-8d5d-aa3f82eff710)

This feature is enabled on the LF account. So the blog post went live at **exactly 08:00**, but the Linkedin post could have been posted **between 07:52 and 08:12**. If it was posted before the blog post was live, it would have been marked as "Page Not Found", as this post was, and as the [post before it also was](https://www.linkedin.com/posts/cloud-native-computing-foundation_page-not-found-cncf-activity-7158851749598941186-xmA1). 

# Fixing the root cause

1) We could [turn off](https://app.hubspot.com/social/8112310/settings/schedule) "Publish like a human" on HubSpot. But this is a shared setting across all LF properties, so turning it off may not be wanted universally so we would need to check this is OK to edit.

or 

2) Schedule LinkedIn posts on HubSpot **at least 10 minutes after they go live on the CNCF blog**. This will then make sure the blog post is always published before the post is created on LinkedIn or on other platforms. Currently the social posts are shared 1-2 minutes after they go live, so the odds of the share happening before the blog post is live is high.

## Testing Social Share Images

To check if a website or the platform is at fault for not displaying the correct social share image you can use a couple of tools to check a pages social share image - [socialsharepreview.com](https://socialsharepreview.com/?url=https://www.cncf.io/blog/2024/02/02/oracle-oci-credits-are-now-available-to-cncf-projects-here-is-what-you-need-to-know/) and also [LinkedIns own social share tool](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.cncf.io%2Fblog%2F2024%2F02%2F02%2Foracle-oci-credits-are-now-available-to-cncf-projects-here-is-what-you-need-to-know%2F)

**Comment by thetwopct** [comment] 2024-02-06 16:30
@cjyabraham Could there also be caching on the server side, so even though the blog post is "published" at 0800 it may not appear to everyone (including social media scheduling tools) until a few more minutes pass? I am thinking of [this issue](https://github.com/cncf/cncf.io/issues/741).

**Comment by thetwopct** [comment] 2024-02-07 08:32
Had the social team try to edit the original LinkedIn post - updating the link with a query param did not trigger re-fetch, and there was no way to add an image or remove the link. So looks like editing after the fact is not possible. They [re-posted the article](https://www.linkedin.com/posts/cloud-native-computing-foundation_oracle-oci-credits-are-now-available-to-cncf-activity-7160912933487583232-wZVa?utm_source=share&utm_medium=member_desktop) and this time the page/image worked.

Have asked social team to experiment with 10 minutes delay added to scheduled posts after blog post schedule posting time.

**Comment by thetwopct** [comment] 2024-02-12 09:44
The social team are now posting 10-15 minutes after the blog posts are scheduled, and this problem seems to have stopped. We will keep an eye on future posts.

**Closed by thetwopct** 2024-02-12 09:44 UTC
