### ISSUE TITLE
Pre-publish checklist

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#277] opened 2020-08-27 13:47 UTC
I've implemented the [Publication Checklist](https://github.com/humanmade/publication-checklist) plugin, written some pre-publication rules and added them to the LF MU plugin.

Rules load [after plugins](https://github.com/cncf/wp-mu-plugins/blob/b6d0ea97384c68ab9d4f874da021041c16ebeb77/lf-mu/includes/class-lf-mu.php#L166) and customisation won't load if the plugin isn't present.

The checklist can be added to/edited in [checklist.php](https://github.com/cncf/wp-mu-plugins/blob/master/lf-mu/admin/partials/checklist.php)

To get us started, I've set up:

- Posts - check image is 1200x630 size (minimum recommended size for social share)
- Webinar - check for topics applied to post
- Case Study - check video is present in body

![20200827144119-Add New Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/91449741-61ec9880-e873-11ea-8cd0-7349fa929b08.jpg)

The checklist displays before publication, or can be accessed using the top nav  to open in the sidebar. 

The checklist only applies to new posts, but it does give the status of the checklist regardless of its post status, so this could be useful for checking that all posts comply with SEO/content rules.

The checklist can be bypassed by the Editor after confirmation they understand they have not met requirements.

![20200827144717-Add New Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/91450432-35854c00-e874-11ea-9c67-4657e7e8fff1.jpg)

**Comment by cjyabraham** [comment] 2020-08-28 02:48
I think this is cool but think we should hold off adding it until it's clear what the paint points are for our editors.  It may turn out to be unnecessary and not worth the extra code and UI distraction.

**Comment by thetwopct** [comment] 2020-08-28 09:19
Poor decision, but I have deactivated the plugin for now.

**Comment by cjyabraham** [comment] 2020-09-02 02:59
When I went to upgrade LFPH to WP 5.5.1 this code started throwing an error:
```
Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /app/web/wp-content/mu-plugins/wp-mu-plugins/lf-mu/admin/class-lf-mu-admin.php:400 Stack trace: #0 /app/web/wp/wp-includes/class-wp-hook.php(287): Lf_Mu_Admin->pre_publish_checklist('') #1 /app/web/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /app/web/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /app/web/wp/wp-settings.php(409): do_action('plugins_loaded') #4 /app/web/wp-config.php(216): require_once('/app/web/wp/wp-...') #5 /app/web/wp/wp-load.php(42): require_once('/app/web/wp-con...') #6 /app/web/wp/wp-blog-header.php(13): require_once('/app/web/wp/wp-...') #7 /app/web/index.php(6): require('/app/web/wp/wp-...') #8 {main} thrown in /app/web/wp-content/mu-plugins/wp-mu-plugins/lf-mu/admin/class-lf-mu-admin.php on line 400
```

I don't know why it doesn't fail as well on CNCF, however, [this seems to be the workaround](https://www.aurodigo.com/2014/08/how-to-solve-fatal-error-call-to-undefined-function-is-plugin-active-problem-on-wordpress.html).

For now, [I've just commented out the pre_publish_checklist hook](https://github.com/cncf/wp-mu-plugins/commit/ee021cae05a55c1226d18000ec4947864333ca01).

**Comment by cjyabraham** [comment] 2020-09-10 03:34
Can we turn off the suggestion to add tags to posts?
<img width="297" alt="Screen Shot 2020-09-10 at 11 24 44 AM" src="https://user-images.githubusercontent.com/463160/92678896-95daba00-f359-11ea-959d-31238a4be209.png">

**Comment by thetwopct** [comment] 2020-09-10 09:19
That isn’t part of the pre-publish checklist module I’ve added, that seems to be part of WordPress.

**Comment by thetwopct** [comment] 2020-09-10 09:28
Just adding this here for my notes and I’ll try to work out how to remove that suggestion 
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-publish-panel/maybe-tags-panel.js

**Comment by cjyabraham** [comment] 2020-09-13 02:09
In prep for deploying this, I [tweaked the checklists](https://github.com/cncf/wp-mu-plugins/commit/62d7a32c64e9c93bff575d3f9989cd7eed8ed796) and also disabled the webinar one because I don’t think the team will need to be reminded again about topics (if I’m wrong, we’ll be able to see and then we can activate it) and, as I say above, it would seem odd to me to remind them about topics but not about other required metadata.  

But I think I've found a more serious problem with this solution.  The checklists only update when you save to the back-end, so often the checklists reflect an inaccurate state of things, which is especially problematic in Gutenberg which is known for showing updates live.  [The issue is best described here](https://github.com/humanmade/publication-checklist/issues/9) and [I've also made a video](https://drive.google.com/file/d/1xphJyUCpky0hcrGeD_0L04zwrOGWYLQ8/view?usp=sharing).

I think we should wait for that to be fixed in the plugin or consider an alternative implementation.

**Comment by thetwopct** [comment] 2020-09-17 19:26
I see your point although I don't think its _serious_. Other plugins (Yoast SEO immediately springs to mind) work exactly the same and require saving a post draft first for the SEO checks to start and give feedback. All content plugins worked like this pre-Gutenberg. Only with Gutenberg are you expecting checks to happen every time a user presses a key or in time with the WP heartbeat. Running an analysis over the content after each key press has potential performance implications in itself.

I would be happy with what we have, and I think it has a benefit to editors regardless of real time feedback. But as you are not happy, I will remove pp-c from the site and MU plugin, and explore how to do this via React.

**Comment by thetwopct** [comment] 2020-09-23 23:36
Digging in to this today and got it working using JS.

![20200924000312-Edit Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/94074433-83e92480-fdf9-11ea-8639-ef3ea5e47cfb.jpg)

Using lockPostSaving() function, it's possible to prevent posts being submitted if conditions are not met. I haven't found an override for this yet so, for instance, if an editor wanted to submit a blog post regardless of the presence of a featured image, and we had made that as a requirement, there would not be a way for them to bypass the requirement (unlike the Human Made plugin we tested).

The JS version of P-PC works much the same as the PHP version, and requires the editor to save the post as a draft or preview the post to start some of the checks (like Featured Image). I am exploring whether it's possible to hook in to the media uploader to trigger the checks via JS.

I did fine one big issue - in that if a post is published, but then edited, the pre-publish checklists no longer show, but the rules still apply. I've been working around this to add a sidebar for the P-PC (like the last plugin) to inform the editor, or I may be able to detect if post has already been published and therefore not apply the rules. 

It would also be useful to define the rules you think we need so I can focus on developing those first.

For Posts (Blog Category Only)

**Recommended rules:**
Add featured image
More than 500 words
No H1 tags
Featured image at least 1200x630 (or some feedback around that)

**Required rules:**
Featured image bigger than 540x285

Any others?

**Comment by cjyabraham** [comment] 2020-09-24 02:33
I don't think we should have any required rules that stop a person from publishing.  You could add a rule to make sure one and only one category is chosen for a post.  The other rules you have there look fine.

For webinars, you could add a rule to make sure a date is set.  There have been a couple instances now where there is no date set.

**Comment by cjyabraham** [comment] 2020-09-30 07:22
Deploying work so far and closing this in favor of [new issue for later work](https://github.com/cncf/cncf.io/issues/340).

**Closed by cjyabraham** 2020-09-30 07:22 UTC
Labels: nice to have
