### ISSUE TITLE
The go-to-top button on mobile moves up and down as I scroll up and down

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#300] opened 2020-08-31 06:38 UTC
Is it possible to have it fixed in one spot?  I can't seem to get a good recording of this because it does it most on my own phone...

**Comment by thetwopct** [comment] 2020-08-31 07:59
It is fixed in one spot. So that's strange. It's not moving on iOS. I'll check with BrowserStack.

**Comment by thetwopct** [comment] 2020-09-18 10:40
I've been through BrowserStack on various devices and I'm unable to reproduce the issue.

Samsung Galaxy S20 Ultra - Android 10 - Chrome
Samsung Galaxy S20 Ultra - Android 10 - Firefox
Samsung Galaxy S8 - Android 7 - Samsung Browser
OnePlus 8 - Android 10 - Chrome
iPhone 11 Pro - iOS 13 - Chrome

The closest I have got it to the button "moving up and down" is this - but this is just the browser being useful to the user when they scroll a certain direction, and the button is still fixed relative to the bottom of the visible page.

![Kapture 2020-09-18 at 12 25 18](https://user-images.githubusercontent.com/10615884/93587334-0614bb80-f9aa-11ea-84ae-d6f7d29d1536.gif)

Is is happening on a particular page (perhaps the annual report page as this has a lot of custom CSS?)
What is your device specs?

**Comment by cjyabraham** [comment] 2020-09-18 12:53
You can try with the Samsung Galaxy A51 in Browserstack.  [Here is the vid](https://drive.google.com/file/d/1FiuJMokGSPQ04QpWoi7d01Roi2wIJKaX/view?usp=sharing).  My phone is the Galaxy A50s and exhibits the same issue.  Since you tested on many other devices and couldn't replicate, and it's not even a big deal when it does happen, I'll double down on this being a nice to have and will put it in the Later column.

**Comment by thetwopct** [comment] 2020-09-18 15:42
I couldn't reproduce using the A51 on Browserstack. Strange! 

Fron the video It's like it's attached to how the URL bar is being displayed, and then the DOM is not updating to reflect the new positions. The button is fixed with CSS, nothing fancy at all. I've experimented with attaching the button to the bottom axis instead of the top, LMK if its fixes it for you. 

Otherwise the only other solution I can see would be JS-based and that seems to be adding a lot of complexity for a small subset of users.

**Comment by cjyabraham** [comment] 2020-09-19 03:07
It's fixed.  Nice job.  It does now sit higher up in the browser.  Is this ok or would you want it to sit lower down as it was before?
<img width="338" alt="Screen Shot 2020-09-19 at 11 06 15 AM" src="https://user-images.githubusercontent.com/463160/93657820-3d49a200-fa68-11ea-8343-c84917a028aa.png">

**Comment by thetwopct** [comment] 2020-09-19 08:46
I'll move it down 20px.

**Closed** 2020-09-21 21:58 UTC
Labels: nice to have
