### ISSUE TITLE
Align date and author on search results

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#170] opened 2020-06-12 05:42 UTC
Narrow browser and mobile views of search results has the dates and authors not aligned on the same line:
<img width="475" alt="Screen Shot 2020-06-12 at 1 39 28 PM" src="https://user-images.githubusercontent.com/463160/84468824-4f21e900-acb2-11ea-9a18-743e20e12851.png">

While you're looking at this, the calendar icon looks about 2 pixels too high throughout the whole site:
<img width="1063" alt="Screen Shot 2020-06-12 at 1 43 56 PM" src="https://user-images.githubusercontent.com/463160/84469074-c9eb0400-acb2-11ea-8c6b-0a24ee7be2c5.png">

**Comment by thetwopct** [comment] 2020-06-12 08:00
I edited the Post icon last night to fix it being slightly off - and I can't reproduce the gap you show. Can you confirm this is still happening? I've checked in multi browsers and cannot reproduce

**Comment by thetwopct** [comment] 2020-06-12 22:55
![20200612221851-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/84547107-b794b880-acfa-11ea-9104-dae13182beff.jpg)

![20200612222342-Dashboard](https://user-images.githubusercontent.com/10615884/84547402-620cdb80-acfb-11ea-8109-eec125e2e862.jpg)

I'm unable to reproduce on dev or local, across Safari, Chrome or Firefox and on IE11 using Browserstack for IE11. I think this is fixed, but may be a cache issue on your system?

**Comment by cjyabraham** [comment] 2020-06-13 03:31
Can you check on [the search results](https://dev-cncfci.pantheonsite.io/?s=partner)?  The first issue is only a problem for me there.  I did confirm that it's a problem in browserstack as well.

The second issue (calendar icon looks about 2 pixels too high) appears throughout the site.  I think I can see it evident in your second screenshot above.

**Comment by thetwopct** [comment] 2020-06-25 01:08
Copied styled from LFPH, so should be closed now

**Closed by thetwopct** 2020-06-25 01:08 UTC
